"""
This type stub file was generated by pyright.
"""

from django.core.cache.backends.base import BaseCache

"File-based cache backend"
class FileBasedCache(BaseCache):
    cache_suffix = ...
    pickle_protocol = ...
    def __init__(self, dir, params) -> None:
        ...
    
    def add(self, key, value, timeout=..., version=...): # -> bool:
        ...
    
    def get(self, key, default=..., version=...): # -> Any | None:
        ...
    
    def set(self, key, value, timeout=..., version=...): # -> None:
        ...
    
    def touch(self, key, timeout=..., version=...): # -> bool:
        ...
    
    def delete(self, key, version=...): # -> bool:
        ...
    
    def has_key(self, key, version=...): # -> bool:
        ...
    
    def clear(self): # -> None:
        """
        Remove all the cache files.
        """
        ...
    


