"""
This type stub file was generated by pyright.
"""

from .. import Tags, register

W003 = ...
W016 = ...
@register(Tags.security, deploy=True)
def check_csrf_middleware(app_configs, **kwargs): # -> list[Warning]:
    ...

@register(Tags.security, deploy=True)
def check_csrf_cookie_secure(app_configs, **kwargs): # -> list[Warning]:
    ...

@register(Tags.security)
def check_csrf_failure_view(app_configs, **kwargs): # -> list[Unknown]:
    ...

