"""
This type stub file was generated by pyright.
"""

import collections.abc
import copy
import datetime
import decimal
import math
import operator
import uuid
import warnings
from base64 import b64decode, b64encode
from functools import partialmethod, total_ordering
from django import forms
from django.apps import apps
from django.conf import settings
from django.core import checks, exceptions, validators
from django.db import connection, connections, router
from django.db.models.constants import LOOKUP_SEP
from django.db.models.query_utils import DeferredAttribute, RegisterLookupMixin
from django.utils import timezone
from django.utils.datastructures import DictWrapper
from django.utils.dateparse import parse_date, parse_datetime, parse_duration, parse_time
from django.utils.duration import duration_microseconds, duration_string
from django.utils.functional import Promise, cached_property
from django.utils.ipv6 import clean_ipv6_address
from django.utils.itercompat import is_iterable
from django.utils.text import capfirst
from django.utils.translation import gettext_lazy as _

__all__ = ["AutoField", "BLANK_CHOICE_DASH", "BigAutoField", "BigIntegerField", "BinaryField", "BooleanField", "CharField", "CommaSeparatedIntegerField", "DateField", "DateTimeField", "DecimalField", "DurationField", "EmailField", "Empty", "Field", "FilePathField", "FloatField", "GenericIPAddressField", "IPAddressField", "IntegerField", "NOT_PROVIDED", "NullBooleanField", "PositiveBigIntegerField", "PositiveIntegerField", "PositiveSmallIntegerField", "SlugField", "SmallAutoField", "SmallIntegerField", "TextField", "TimeField", "URLField", "UUIDField"]
class Empty:
    ...


class NOT_PROVIDED:
    ...


BLANK_CHOICE_DASH = ...
def return_None(): # -> None:
    ...

@total_ordering
class Field(RegisterLookupMixin):
    """Base class for all field types"""
    empty_strings_allowed = ...
    empty_values = ...
    creation_counter = ...
    auto_creation_counter = ...
    default_validators = ...
    default_error_messages = ...
    system_check_deprecated_details = ...
    system_check_removed_details = ...
    non_db_attrs = ...
    hidden = ...
    many_to_many = ...
    many_to_one = ...
    one_to_many = ...
    one_to_one = ...
    related_model = ...
    descriptor_class = DeferredAttribute
    description = ...
    def __init__(self, verbose_name=..., name=..., primary_key=..., max_length=..., unique=..., blank=..., null=..., db_index=..., rel=..., default=..., editable=..., serialize=..., unique_for_date=..., unique_for_month=..., unique_for_year=..., choices=..., help_text=..., db_column=..., db_tablespace=..., auto_created=..., validators=..., error_messages=...) -> None:
        ...
    
    def __str__(self) -> str:
        """
        Return "app_label.model_label.field_name" for fields attached to
        models.
        """
        ...
    
    def __repr__(self): # -> str:
        """Display the module, class, and name of the field."""
        ...
    
    def check(self, **kwargs): # -> list[Unknown]:
        ...
    
    def get_col(self, alias, output_field=...): # -> cached_property | Col:
        ...
    
    @cached_property
    def cached_col(self): # -> Col:
        ...
    
    def select_format(self, compiler, sql, params): # -> tuple[Unknown, Unknown]:
        """
        Custom format for select clauses. For example, GIS columns need to be
        selected as AsText(table.col) on MySQL as the table.col data can't be
        used by Django.
        """
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        """
        Return enough information to recreate the field as a 4-tuple:

         * The name of the field on the model, if contribute_to_class() has
           been run.
         * The import path of the field, including the class, e.g.
           django.db.models.IntegerField. This should be the most portable
           version, so less specific may be better.
         * A list of positional arguments.
         * A dict of keyword arguments.

        Note that the positional or keyword arguments must contain values of
        the following types (including inner values of collection types):

         * None, bool, str, int, float, complex, set, frozenset, list, tuple,
           dict
         * UUID
         * datetime.datetime (naive), datetime.date
         * top-level classes, top-level functions - will be referenced by their
           full import path
         * Storage instances - these have their own deconstruct() method

        This is because the values here must be serialized into a text format
        (possibly new Python code, possibly JSON) and these are the only types
        with encoding handlers defined.

        There's no need to return the exact way the field was instantiated this
        time, just ensure that the resulting field is the same - prefer keyword
        arguments over positional ones, and omit parameters with their default
        values.
        """
        ...
    
    def clone(self): # -> Field:
        """
        Uses deconstruct() to clone a new copy of this Field.
        Will not preserve any class attachments/attribute names.
        """
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __deepcopy__(self, memodict): # -> Self@Field:
        ...
    
    def __copy__(self): # -> Empty:
        ...
    
    def __reduce__(self): # -> tuple[(of_cls: Unknown) -> Empty, tuple[Type[Field]], dict[str, Any]] | tuple[(app_label: Unknown, model_name: Unknown, field_name: Unknown) -> Unknown, tuple[Unknown, Unknown, Unknown | None]]:
        """
        Pickling should return the model._meta.fields instance of the field,
        not a new copy of that field. So, use the app registry to load the
        model and then the field back.
        """
        ...
    
    def get_pk_value_on_save(self, instance): # -> None:
        """
        Hook to generate new PK values on save. This method is called when
        saving instances with no primary key value set. If this method returns
        something else than None, then the returned value is used when saving
        the new instance.
        """
        ...
    
    def to_python(self, value):
        """
        Convert the input value into the expected Python data type, raising
        django.core.exceptions.ValidationError if the data can't be converted.
        Return the converted value. Subclasses should override this.
        """
        ...
    
    @cached_property
    def error_messages(self): # -> dict[Unknown, Unknown]:
        ...
    
    @cached_property
    def validators(self): # -> list[Unknown]:
        """
        Some validators can't be created at field initialization time.
        This method provides a way to delay their creation until required.
        """
        ...
    
    def run_validators(self, value): # -> None:
        ...
    
    def validate(self, value, model_instance): # -> None:
        """
        Validate value and raise ValidationError if necessary. Subclasses
        should override this to provide validation logic.
        """
        ...
    
    def clean(self, value, model_instance):
        """
        Convert the value's type and run validation. Validation errors
        from to_python() and validate() are propagated. Return the correct
        value if no error is raised.
        """
        ...
    
    def db_type_parameters(self, connection): # -> DictWrapper:
        ...
    
    def db_check(self, connection): # -> None:
        """
        Return the database column check constraint for this field, for the
        provided connection. Works the same way as db_type() for the case that
        get_internal_type() does not map to a preexisting model field.
        """
        ...
    
    def db_type(self, connection): # -> None:
        """
        Return the database column data type for this field, for the provided
        connection.
        """
        ...
    
    def rel_db_type(self, connection): # -> None:
        """
        Return the data type that a related field pointing to this field should
        use. For example, this method is called by ForeignKey and OneToOneField
        to determine its data type.
        """
        ...
    
    def cast_db_type(self, connection): # -> None:
        """Return the data type to use in the Cast() function."""
        ...
    
    def db_parameters(self, connection): # -> dict[str, Unknown | None]:
        """
        Extension of db_type(), providing a range of different return values
        (type, checks). This will look at db_type(), allowing custom model
        fields to override it.
        """
        ...
    
    def db_type_suffix(self, connection):
        ...
    
    def get_db_converters(self, connection): # -> list[Unknown]:
        ...
    
    @property
    def unique(self): # -> bool:
        ...
    
    @property
    def db_tablespace(self): # -> Any:
        ...
    
    @property
    def db_returning(self): # -> Literal[False]:
        """
        Private API intended only to be used by Django itself. Currently only
        the PostgreSQL backend supports returning multiple fields on a model.
        """
        ...
    
    def set_attributes_from_name(self, name): # -> None:
        ...
    
    def contribute_to_class(self, cls, name, private_only=...): # -> None:
        """
        Register the field with the model class it belongs to.

        If private_only is True, create a separate instance of this field
        for every subclass of cls, even if cls is not an abstract model.
        """
        ...
    
    def get_filter_kwargs_for_object(self, obj): # -> dict[Unknown | None, Any]:
        """
        Return a dict that when passed as kwargs to self.model.filter(), would
        yield all instances having the same value for this field as obj has.
        """
        ...
    
    def get_attname(self): # -> None:
        ...
    
    def get_attname_column(self): # -> tuple[Unknown | None, Unknown | None]:
        ...
    
    def get_internal_type(self): # -> str:
        ...
    
    def pre_save(self, model_instance, add): # -> Any:
        """Return field's value just before saving."""
        ...
    
    def get_prep_value(self, value):
        """Perform preliminary non-db specific value checks and conversions."""
        ...
    
    def get_db_prep_value(self, value, connection, prepared=...):
        """
        Return field's value prepared for interacting with the database backend.

        Used by the default implementations of get_db_prep_save().
        """
        ...
    
    def get_db_prep_save(self, value, connection):
        """Return field's value prepared for saving into a database."""
        ...
    
    def has_default(self): # -> bool:
        """Return a boolean of whether this field has a default value."""
        ...
    
    def get_default(self):
        """Return the default value for this field."""
        ...
    
    def get_choices(self, include_blank=..., blank_choice=..., limit_choices_to=..., ordering=...): # -> list[Unknown]:
        """
        Return choices with a default blank choices included, for use
        as <select> choices for this field.
        """
        ...
    
    def value_to_string(self, obj): # -> str:
        """
        Return a string value of this field from the passed obj.
        This is used by the serialization framework.
        """
        ...
    
    flatchoices = ...
    def save_form_data(self, instance, data): # -> None:
        ...
    
    def formfield(self, form_class=..., choices_form_class=..., **kwargs): # -> CharField | TypedChoiceField:
        """Return a django.forms.Field instance for this field."""
        ...
    
    def value_from_object(self, obj): # -> Any:
        """Return the value of this field in the given model instance."""
        ...
    


class BooleanField(Field):
    empty_strings_allowed = ...
    default_error_messages = ...
    description = ...
    def get_internal_type(self): # -> Literal['BooleanField']:
        ...
    
    def to_python(self, value): # -> bool | None:
        ...
    
    def get_prep_value(self, value): # -> bool | None:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    
    def select_format(self, compiler, sql, params): # -> tuple[Unknown | Literal['1'], Unknown]:
        ...
    


class CharField(Field):
    description = ...
    def __init__(self, *args, db_collation=..., **kwargs) -> None:
        ...
    
    def check(self, **kwargs): # -> list[Unknown]:
        ...
    
    def cast_db_type(self, connection): # -> None:
        ...
    
    def db_parameters(self, connection): # -> dict[str, Unknown | None]:
        ...
    
    def get_internal_type(self): # -> Literal['CharField']:
        ...
    
    def to_python(self, value): # -> str:
        ...
    
    def get_prep_value(self, value): # -> str:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    


class CommaSeparatedIntegerField(CharField):
    default_validators = ...
    description = ...
    system_check_removed_details = ...


class DateTimeCheckMixin:
    def check(self, **kwargs): # -> list[Unknown]:
        ...
    


class DateField(DateTimeCheckMixin, Field):
    empty_strings_allowed = ...
    default_error_messages = ...
    description = ...
    def __init__(self, verbose_name=..., name=..., auto_now=..., auto_now_add=..., **kwargs) -> None:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    
    def get_internal_type(self): # -> Literal['DateField']:
        ...
    
    def to_python(self, value): # -> _Date:
        ...
    
    def pre_save(self, model_instance, add): # -> date | Any:
        ...
    
    def contribute_to_class(self, cls, name, **kwargs): # -> None:
        ...
    
    def get_prep_value(self, value): # -> _Date:
        ...
    
    def get_db_prep_value(self, value, connection, prepared=...):
        ...
    
    def value_to_string(self, obj): # -> Any | Literal['']:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class DateTimeField(DateField):
    empty_strings_allowed = ...
    default_error_messages = ...
    description = ...
    def get_internal_type(self): # -> Literal['DateTimeField']:
        ...
    
    def to_python(self, value): # -> datetime | Any:
        ...
    
    def pre_save(self, model_instance, add): # -> datetime | date | Any:
        ...
    
    def get_prep_value(self, value): # -> Any | datetime:
        ...
    
    def get_db_prep_value(self, value, connection, prepared=...):
        ...
    
    def value_to_string(self, obj): # -> Any | Literal['']:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class DecimalField(Field):
    empty_strings_allowed = ...
    default_error_messages = ...
    description = ...
    def __init__(self, verbose_name=..., name=..., max_digits=..., decimal_places=..., **kwargs) -> None:
        ...
    
    def check(self, **kwargs): # -> list[Unknown]:
        ...
    
    @cached_property
    def validators(self):
        ...
    
    @cached_property
    def context(self): # -> Context:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    
    def get_internal_type(self): # -> Literal['DecimalField']:
        ...
    
    def to_python(self, value): # -> Decimal:
        ...
    
    def get_db_prep_save(self, value, connection):
        ...
    
    def get_prep_value(self, value): # -> Decimal:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class DurationField(Field):
    """
    Store timedelta objects.

    Use interval on PostgreSQL, INTERVAL DAY TO SECOND on Oracle, and bigint
    of microseconds on other databases.
    """
    empty_strings_allowed = ...
    default_error_messages = ...
    description = ...
    def get_internal_type(self): # -> Literal['DurationField']:
        ...
    
    def to_python(self, value): # -> timedelta:
        ...
    
    def get_db_prep_value(self, value, connection, prepared=...): # -> None:
        ...
    
    def get_db_converters(self, connection): # -> list[Unknown]:
        ...
    
    def value_to_string(self, obj): # -> str:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class EmailField(CharField):
    default_validators = ...
    description = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class FilePathField(Field):
    description = ...
    def __init__(self, verbose_name=..., name=..., path=..., match=..., recursive=..., allow_files=..., allow_folders=..., **kwargs) -> None:
        ...
    
    def check(self, **kwargs): # -> list[Unknown]:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    
    def get_prep_value(self, value): # -> str | None:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    
    def get_internal_type(self): # -> Literal['FilePathField']:
        ...
    


class FloatField(Field):
    empty_strings_allowed = ...
    default_error_messages = ...
    description = ...
    def get_prep_value(self, value): # -> float | None:
        ...
    
    def get_internal_type(self): # -> Literal['FloatField']:
        ...
    
    def to_python(self, value): # -> float:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class IntegerField(Field):
    empty_strings_allowed = ...
    default_error_messages = ...
    description = ...
    def check(self, **kwargs): # -> list[Unknown]:
        ...
    
    @cached_property
    def validators(self): # -> cached_property:
        ...
    
    def get_prep_value(self, value): # -> int | None:
        ...
    
    def get_internal_type(self): # -> Literal['IntegerField']:
        ...
    
    def to_python(self, value): # -> int:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class BigIntegerField(IntegerField):
    description = ...
    MAX_BIGINT = ...
    def get_internal_type(self): # -> Literal['BigIntegerField']:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class SmallIntegerField(IntegerField):
    description = ...
    def get_internal_type(self): # -> Literal['SmallIntegerField']:
        ...
    


class IPAddressField(Field):
    empty_strings_allowed = ...
    description = ...
    system_check_removed_details = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    
    def get_prep_value(self, value): # -> str | None:
        ...
    
    def get_internal_type(self): # -> Literal['IPAddressField']:
        ...
    


class GenericIPAddressField(Field):
    empty_strings_allowed = ...
    description = ...
    default_error_messages = ...
    def __init__(self, verbose_name=..., name=..., protocol=..., unpack_ipv4=..., *args, **kwargs) -> None:
        ...
    
    def check(self, **kwargs): # -> list[Unknown]:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    
    def get_internal_type(self): # -> Literal['GenericIPAddressField']:
        ...
    
    def to_python(self, value): # -> str | None:
        ...
    
    def get_db_prep_value(self, value, connection, prepared=...):
        ...
    
    def get_prep_value(self, value): # -> str | None:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class NullBooleanField(BooleanField):
    default_error_messages = ...
    description = ...
    system_check_removed_details = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    


class PositiveIntegerRelDbTypeMixin:
    def __init_subclass__(cls, **kwargs): # -> None:
        ...
    
    def rel_db_type(self, connection): # -> None:
        """
        Return the data type that a related field pointing to this field should
        use. In most cases, a foreign key pointing to a positive integer
        primary key will have an integer column data type but some databases
        (e.g. MySQL) have an unsigned integer type. In that case
        (related_fields_match_type=True), the primary key should return its
        db_type.
        """
        ...
    


class PositiveBigIntegerField(PositiveIntegerRelDbTypeMixin, BigIntegerField):
    description = ...
    def get_internal_type(self): # -> Literal['PositiveBigIntegerField']:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class PositiveIntegerField(PositiveIntegerRelDbTypeMixin, IntegerField):
    description = ...
    def get_internal_type(self): # -> Literal['PositiveIntegerField']:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class PositiveSmallIntegerField(PositiveIntegerRelDbTypeMixin, SmallIntegerField):
    description = ...
    def get_internal_type(self): # -> Literal['PositiveSmallIntegerField']:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class SlugField(CharField):
    default_validators = ...
    description = ...
    def __init__(self, *args, max_length=..., db_index=..., allow_unicode=..., **kwargs) -> None:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    
    def get_internal_type(self): # -> Literal['SlugField']:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class TextField(Field):
    description = ...
    def __init__(self, *args, db_collation=..., **kwargs) -> None:
        ...
    
    def check(self, **kwargs): # -> list[Unknown]:
        ...
    
    def db_parameters(self, connection): # -> dict[str, Unknown | None]:
        ...
    
    def get_internal_type(self): # -> Literal['TextField']:
        ...
    
    def to_python(self, value): # -> str:
        ...
    
    def get_prep_value(self, value): # -> str:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    


class TimeField(DateTimeCheckMixin, Field):
    empty_strings_allowed = ...
    default_error_messages = ...
    description = ...
    def __init__(self, verbose_name=..., name=..., auto_now=..., auto_now_add=..., **kwargs) -> None:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    
    def get_internal_type(self): # -> Literal['TimeField']:
        ...
    
    def to_python(self, value): # -> time | None:
        ...
    
    def pre_save(self, model_instance, add): # -> _Time | Any:
        ...
    
    def get_prep_value(self, value): # -> time | None:
        ...
    
    def get_db_prep_value(self, value, connection, prepared=...):
        ...
    
    def value_to_string(self, obj): # -> Any | Literal['']:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class URLField(CharField):
    default_validators = ...
    description = ...
    def __init__(self, verbose_name=..., name=..., **kwargs) -> None:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class BinaryField(Field):
    description = ...
    empty_values = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def check(self, **kwargs): # -> list[Unknown]:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    
    def get_internal_type(self): # -> Literal['BinaryField']:
        ...
    
    def get_placeholder(self, value, compiler, connection):
        ...
    
    def get_default(self): # -> Literal[b""]:
        ...
    
    def get_db_prep_value(self, value, connection, prepared=...):
        ...
    
    def value_to_string(self, obj): # -> str:
        """Binary data is serialized as base64"""
        ...
    
    def to_python(self, value): # -> memoryview:
        ...
    


class UUIDField(Field):
    default_error_messages = ...
    description = ...
    empty_strings_allowed = ...
    def __init__(self, verbose_name=..., **kwargs) -> None:
        ...
    
    def deconstruct(self): # -> tuple[Unknown | None, str, list[Unknown], dict[Unknown, Unknown]]:
        ...
    
    def get_internal_type(self): # -> Literal['UUIDField']:
        ...
    
    def get_prep_value(self, value): # -> UUID:
        ...
    
    def get_db_prep_value(self, value, connection, prepared=...): # -> UUID | str | None:
        ...
    
    def to_python(self, value): # -> UUID:
        ...
    
    def formfield(self, **kwargs): # -> CharField | TypedChoiceField:
        ...
    


class AutoFieldMixin:
    db_returning = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def check(self, **kwargs): # -> list[Unknown]:
        ...
    
    def deconstruct(self): # -> tuple[Unknown, Unknown, Unknown, Unknown]:
        ...
    
    def validate(self, value, model_instance): # -> None:
        ...
    
    def get_db_prep_value(self, value, connection, prepared=...):
        ...
    
    def contribute_to_class(self, cls, name, **kwargs): # -> None:
        ...
    
    def formfield(self, **kwargs): # -> None:
        ...
    


class AutoFieldMeta(type):
    """
    Metaclass to maintain backward inheritance compatibility for AutoField.

    It is intended that AutoFieldMixin become public API when it is possible to
    create a non-integer automatically-generated field using column defaults
    stored in the database.

    In many areas Django also relies on using isinstance() to check for an
    automatically-generated field as a subclass of AutoField. A new flag needs
    to be implemented on Field to be used instead.

    When these issues have been addressed, this metaclass could be used to
    deprecate inheritance from AutoField and use of isinstance() with AutoField
    for detecting automatically-generated fields.
    """
    def __instancecheck__(self, instance): # -> bool:
        ...
    
    def __subclasscheck__(self, subclass): # -> bool:
        ...
    


class AutoField(AutoFieldMixin, IntegerField, metaclass=AutoFieldMeta):
    def get_internal_type(self): # -> Literal['AutoField']:
        ...
    
    def rel_db_type(self, connection): # -> None:
        ...
    


class BigAutoField(AutoFieldMixin, BigIntegerField):
    def get_internal_type(self): # -> Literal['BigAutoField']:
        ...
    
    def rel_db_type(self, connection): # -> None:
        ...
    


class SmallAutoField(AutoFieldMixin, SmallIntegerField):
    def get_internal_type(self): # -> Literal['SmallAutoField']:
        ...
    
    def rel_db_type(self, connection): # -> None:
        ...
    


