"""
This type stub file was generated by pyright.
"""

from django.utils.functional import cached_property
from .base import BaseEngine

class Jinja2(BaseEngine):
    app_dirname = ...
    def __init__(self, params) -> None:
        ...
    
    def from_string(self, template_code): # -> Template:
        ...
    
    def get_template(self, template_name): # -> Template:
        ...
    
    @cached_property
    def template_context_processors(self): # -> list[Any]:
        ...
    


class Template:
    def __init__(self, template, backend) -> None:
        ...
    
    def render(self, context=..., request=...):
        ...
    


class Origin:
    """
    A container to hold debug information as described in the template API
    documentation.
    """
    def __init__(self, name, template_name) -> None:
        ...
    


def get_exception_info(exception): # -> dict[str, Unknown]:
    """
    Format exception information for display on the debug page using the
    structure described in the template API documentation.
    """
    ...

