"""
This type stub file was generated by pyright.
"""

"""
Email message and email sending related helper functions.
"""
class CachedDnsName:
    def __str__(self) -> str:
        ...
    
    def get_fqdn(self): # -> str:
        ...
    


DNS_NAME = ...
