"""
This type stub file was generated by pyright.
"""

def matches_patterns(path, patterns): # -> bool:
    """
    Return True or False depending on whether the ``path`` should be
    ignored (if it matches any pattern in ``ignore_patterns``).
    """
    ...

def get_files(storage, ignore_patterns=..., location=...): # -> Generator[str | Unknown, None, None]:
    """
    Recursively walk the storage directories yielding the paths
    of all files that should be copied.
    """
    ...

def check_settings(base_url=...): # -> None:
    """
    Check if the staticfiles settings have sane values.
    """
    ...

