"""
This type stub file was generated by pyright.
"""

from .. import Tags, register

@register(Tags.compatibility)
def check_csrf_trusted_origins(app_configs, **kwargs): # -> list[Unknown]:
    ...

