"""
This type stub file was generated by pyright.
"""

from . import Tags, register

@register(Tags.files)
def check_setting_file_upload_temp_dir(app_configs, **kwargs): # -> list[Error] | list[Unknown]:
    ...

