"""
This type stub file was generated by pyright.
"""

DEBUG = ...
INFO = ...
WARNING = ...
ERROR = ...
CRITICAL = ...
class CheckMessage:
    def __init__(self, level, msg, hint=..., obj=..., id=...) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def is_serious(self, level=...): # -> bool:
        ...
    
    def is_silenced(self): # -> bool:
        ...
    


class Debug(CheckMessage):
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class Info(CheckMessage):
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class Warning(CheckMessage):
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class Error(CheckMessage):
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class Critical(CheckMessage):
    def __init__(self, *args, **kwargs) -> None:
        ...
    


