"""
This type stub file was generated by pyright.
"""

from django.core.checks import Tags, register

@register(Tags.models)
def check_all_models(app_configs=..., **kwargs): # -> list[Unknown]:
    ...

@register(Tags.models)
def check_lazy_references(app_configs=..., **kwargs): # -> list[Unknown] | list[Error | Unknown]:
    ...

