"""
This type stub file was generated by pyright.
"""

from . import Tags, register

@register(Tags.urls)
def check_url_config(app_configs, **kwargs): # -> Any | list[Error] | list[Unknown]:
    ...

def check_resolver(resolver): # -> Any | list[Error] | list[Unknown]:
    """
    Recursively check the resolver.
    """
    ...

@register(Tags.urls)
def check_url_namespaces_unique(app_configs, **kwargs): # -> list[Unknown]:
    """
    Warn if URL namespaces used in applications aren't unique.
    """
    ...

def get_warning_for_invalid_pattern(pattern): # -> list[Error]:
    """
    Return a list containing a warning that the pattern is invalid.

    describe_pattern() cannot be used here, because we cannot rely on the
    urlpattern having regex or name attributes.
    """
    ...

@register(Tags.urls)
def check_url_settings(app_configs, **kwargs): # -> list[Unknown]:
    ...

def E006(name): # -> Error:
    ...

