"""
This type stub file was generated by pyright.
"""

"""
Move a file in the safest way possible::

    >>> from django.core.files.move import file_move_safe
    >>> file_move_safe("/tmp/old_file", "/tmp/new_file")
"""
__all__ = ["file_move_safe"]
def file_move_safe(old_file_name, new_file_name, chunk_size=..., allow_overwrite=...): # -> None:
    """
    Move a file from one location to another in the safest way possible.

    First, try ``os.rename``, which is simple but will break across filesystems.
    If that fails, stream manually from one file to another in pure Python.

    If the destination file exists and ``allow_overwrite`` is ``False``, raise
    ``FileExistsError``.
    """
    ...

