"""
This type stub file was generated by pyright.
"""

def safe_join(base, *paths):
    """
    Join one or more path components to the base path component intelligently.
    Return a normalized, absolute version of the final path.

    Raise ValueError if the final path isn't located inside of the base path
    component.
    """
    ...

def symlinks_supported(): # -> bool:
    """
    Return whether or not creating symlinks are supported in the host platform
    and/or if they are allowed to be created (e.g. on Windows it requires admin
    permissions).
    """
    ...

def to_path(value): # -> Path:
    """Convert value to a pathlib.Path instance, if not already a Path."""
    ...

