"""
This type stub file was generated by pyright.
"""

from django.utils.functional import cached_property

class ConnectionProxy:
    """Proxy for accessing a connection object's attributes."""
    def __init__(self, connections, alias) -> None:
        ...
    
    def __getattr__(self, item): # -> Any:
        ...
    
    def __setattr__(self, name, value): # -> None:
        ...
    
    def __delattr__(self, name): # -> None:
        ...
    
    def __contains__(self, key): # -> bool:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    


class ConnectionDoesNotExist(Exception):
    ...


class BaseConnectionHandler:
    settings_name = ...
    exception_class = ConnectionDoesNotExist
    thread_critical = ...
    def __init__(self, settings=...) -> None:
        ...
    
    @cached_property
    def settings(self): # -> Any:
        ...
    
    def configure_settings(self, settings): # -> Any:
        ...
    
    def create_connection(self, alias):
        ...
    
    def __getitem__(self, alias): # -> Any:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def __delitem__(self, key): # -> None:
        ...
    
    def __iter__(self):
        ...
    
    def all(self, initialized_only=...): # -> list[Any | Unknown]:
        ...
    
    def close_all(self): # -> None:
        ...
    


