"""
This type stub file was generated by pyright.
"""

def duration_string(duration): # -> str:
    """Version of str(timedelta) which is not English specific."""
    ...

def duration_iso_string(duration): # -> str:
    ...

def duration_microseconds(delta):
    ...

