"""
This type stub file was generated by pyright.
"""

import functools

PY36 = ...
PY37 = ...
PY38 = ...
PY39 = ...
PY310 = ...
PY311 = ...
def get_version(version=...): # -> str:
    """Return a PEP 440-compliant version number from VERSION."""
    ...

def get_main_version(version=...): # -> str:
    """Return main version (X.Y[.Z]) from VERSION."""
    ...

def get_complete_version(version=...): # -> tuple[Literal[4], Literal[1], Literal[7], Literal['final'], Literal[0]]:
    """
    Return a tuple of the django version. If version argument is non-empty,
    check for correctness of the tuple provided.
    """
    ...

def get_docs_version(version=...): # -> str:
    ...

@functools.lru_cache
def get_git_changeset(): # -> str | None:
    """Return a numeric identifier of the latest git changeset.

    The result is the UTC timestamp of the changeset in YYYYMMDDHHMMSS format.
    This value isn't guaranteed to be unique, but collisions are very unlikely,
    so it's sufficient for generating the development version numbers.
    """
    ...

version_component_re = ...
def get_version_tuple(version): # -> tuple[Unknown, ...]:
    """
    Return a tuple of version numbers (e.g. (1, 2, 3)) from the version
    string (e.g. '1.2.3').
    """
    ...

