"""
This type stub file was generated by pyright.
"""

from http import cookies

SimpleCookie = cookies.SimpleCookie
def parse_cookie(cookie): # -> dict[Unknown, Unknown]:
    """
    Return a dictionary parsed from a `Cookie:` header string.
    """
    ...

