"""
This type stub file was generated by pyright.
"""

from django.db import DatabaseError

class AmbiguityError(Exception):
    """More than one migration matches a name prefix."""
    ...


class BadMigrationError(Exception):
    """There's a bad migration (unreadable/bad format/etc.)."""
    ...


class CircularDependencyError(Exception):
    """There's an impossible-to-resolve circular dependency."""
    ...


class InconsistentMigrationHistory(Exception):
    """An applied migration has some of its dependencies not applied."""
    ...


class InvalidBasesError(ValueError):
    """A model's base classes can't be resolved."""
    ...


class IrreversibleError(RuntimeError):
    """An irreversible migration is about to be reversed."""
    ...


class NodeNotFoundError(LookupError):
    """An attempt on a node is made that is not available in the graph."""
    def __init__(self, message, node, origin=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> LiteralString:
        ...
    


class MigrationSchemaMissing(DatabaseError):
    ...


class InvalidMigrationPlan(ValueError):
    ...


