"""
This type stub file was generated by pyright.
"""

_prefixes = ...
_urlconfs = ...
def resolve(path, urlconf=...): # -> ResolverMatch:
    ...

def reverse(viewname, urlconf=..., args=..., kwargs=..., current_app=...): # -> str:
    ...

reverse_lazy = ...
def clear_url_caches(): # -> None:
    ...

def set_script_prefix(prefix): # -> None:
    """
    Set the script prefix for the current thread.
    """
    ...

def get_script_prefix(): # -> Any | str:
    """
    Return the currently active script prefix. Useful for client code that
    wishes to construct their own URLs manually (although accessing the request
    instance is normally going to be a lot cleaner).
    """
    ...

def clear_script_prefix(): # -> None:
    """
    Unset the script prefix for the current thread.
    """
    ...

def set_urlconf(urlconf_name): # -> None:
    """
    Set the URLconf for the current thread (overriding the default one in
    settings). If urlconf_name is None, revert back to the default.
    """
    ...

def get_urlconf(default=...): # -> Any | None:
    """
    Return the root URLconf to use for the current thread if it has been
    changed from the default one.
    """
    ...

def is_valid_path(path, urlconf=...): # -> ResolverMatch | Literal[False]:
    """
    Return the ResolverMatch if the given path resolves against the default URL
    resolver, False otherwise. This is a convenience method to make working
    with "is this a match?" cases easier, avoiding try...except blocks.
    """
    ...

def translate_url(url, lang_code): # -> str:
    """
    Given a URL (absolute or relative), try to get its translated version in
    the `lang_code` language (either by i18n_patterns or by translated regex).
    Return the original URL if no translated version is found.
    """
    ...

