"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Mapping, Type
from botocore.model import OperationModel

DEFAULT_TIMESTAMP_FORMAT: str
ISO8601: str
ISO8601_MICRO: str
def create_serializer(protocol_name: str, include_validation: bool = ...) -> Any:
    ...

class Serializer:
    DEFAULT_METHOD: str = ...
    MAP_TYPE: Type[Dict[str, Any]] = ...
    DEFAULT_ENCODING: str = ...
    def serialize_to_request(self, parameters: Mapping[str, Any], operation_model: OperationModel) -> Dict[str, Any]:
        ...
    


class QuerySerializer(Serializer):
    TIMESTAMP_FORMAT: str = ...
    def serialize_to_request(self, parameters: Mapping[str, Any], operation_model: OperationModel) -> Dict[str, Any]:
        ...
    


class EC2Serializer(QuerySerializer):
    ...


class JSONSerializer(Serializer):
    TIMESTAMP_FORMAT: str = ...
    def serialize_to_request(self, parameters: Mapping[str, Any], operation_model: OperationModel) -> Dict[str, Any]:
        ...
    


class BaseRestSerializer(Serializer):
    QUERY_STRING_TIMESTAMP_FORMAT: str = ...
    HEADER_TIMESTAMP_FORMAT: str = ...
    KNOWN_LOCATIONS: Any = ...
    def serialize_to_request(self, parameters: Mapping[str, Any], operation_model: OperationModel) -> Dict[str, Any]:
        ...
    


class RestJSONSerializer(BaseRestSerializer, JSONSerializer):
    ...


class RestXMLSerializer(BaseRestSerializer):
    TIMESTAMP_FORMAT: str = ...


SERIALIZERS: Dict[str, Serializer]
