"""
This type stub file was generated by pyright.
"""

from logging import Logger
from typing import Any, Callable, List, Mapping
from botocore.client import BaseClient

logger: Logger = ...
def create_waiter_with_client(waiter_name: str, waiter_model: WaiterModel, client: BaseClient) -> Waiter:
    ...

def is_valid_waiter_error(response: Mapping[str, Any]) -> bool:
    ...

class NormalizedOperationMethod:
    def __init__(self, client_method: Callable[..., None]) -> None:
        ...
    
    def __call__(self, **kwargs: Any) -> Any:
        ...
    


class WaiterModel:
    SUPPORTED_VERSION: int = ...
    def __init__(self, waiter_config: Mapping[str, Any]) -> None:
        ...
    
    def get_waiter(self, waiter_name: str) -> SingleWaiterConfig:
        ...
    


class SingleWaiterConfig:
    def __init__(self, single_waiter_config: Mapping[str, Any]) -> None:
        ...
    
    @property
    def acceptors(self) -> List[AcceptorConfig]:
        ...
    


class AcceptorConfig:
    def __init__(self, config: Mapping[str, Any]) -> None:
        ...
    
    @property
    def explanation(self) -> str:
        ...
    


class Waiter:
    def __init__(self, name: str, config: Mapping[str, Any], operation_method: Callable[..., Any]) -> None:
        ...
    
    def wait(self, **kwargs: Any) -> None:
        ...
    


