"""
This type stub file was generated by pyright.
"""

from typing import Dict
from awscrt.auth import AwsCredentials
from botocore.auth import BaseSigner as BaseSigner
from botocore.awsrequest import AWSRequest

class CrtSigV4Auth(BaseSigner):
    REQUIRES_REGION: bool = ...
    def __init__(self, credentials: AwsCredentials, service_name: str, region_name: str) -> None:
        ...
    
    def add_auth(self, request: AWSRequest) -> None:
        ...
    


class CrtS3SigV4Auth(CrtSigV4Auth):
    ...


class CrtSigV4AsymAuth(BaseSigner):
    REQUIRES_REGION: bool = ...
    def __init__(self, credentials: AwsCredentials, service_name: str, region_name: str) -> None:
        ...
    
    def add_auth(self, request: AWSRequest) -> None:
        ...
    


class CrtS3SigV4AsymAuth(CrtSigV4AsymAuth):
    ...


class CrtSigV4AsymQueryAuth(CrtSigV4AsymAuth):
    DEFAULT_EXPIRES: int = ...
    def __init__(self, credentials: AwsCredentials, service_name: str, region_name: str, expires: int = ...) -> None:
        ...
    


class CrtS3SigV4AsymQueryAuth(CrtSigV4AsymQueryAuth):
    ...


class CrtSigV4QueryAuth(CrtSigV4Auth):
    DEFAULT_EXPIRES: int = ...
    def __init__(self, credentials: AwsCredentials, service_name: str, region_name: str, expires: int = ...) -> None:
        ...
    


class CrtS3SigV4QueryAuth(CrtSigV4QueryAuth):
    ...


CRT_AUTH_TYPE_MAPS: Dict[str, BaseSigner] = ...
