"""
This type stub file was generated by pyright.
"""

class FixDecimalInputMixin:
    def as_postgresql(self, compiler, connection, **extra_context):
        ...
    


class FixDurationInputMixin:
    def as_mysql(self, compiler, connection, **extra_context): # -> tuple[Unknown, Unknown]:
        ...
    
    def as_oracle(self, compiler, connection, **extra_context):
        ...
    


class NumericOutputFieldMixin:
    ...


