"""
This type stub file was generated by pyright.
"""

from enum import Enum

"""
Constants used across the ORM in general.
"""
LOOKUP_SEP = ...
class OnConflict(Enum):
    IGNORE = ...
    UPDATE = ...


