# Generated by Django 4.1.7 on 2023-04-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
