name: cdk

on:
  push:
    branches:
        - master
  pull_request:
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: yarn
          cache-dependency-path: | 
            resource/yarn.lock

      - name: Setup dependencies
        working-directory: resource
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: resource
        run: yarn build

      - name: Unit tests
        if: contains(github.event_name, 'pull_request')
        working-directory: resource
        run: yarn test:app
          
      - name: CDK Diff Check
        if: contains(github.event_name, 'pull_request')
        working-directory: resource
        run: yarn cdk:diff
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        working-directory: resource
        run: yarn cdk:deploy
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}